[tool.poetry]
name = "mlu"
version = "0.1.0"
description = ""
authors = ["babdus <babdusi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^1.5.3"
streamlit = "^1.20.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
